### ISSUE TITLE
update 1.0.0-beta.7 ssr renderComponent computed error

### ISSUE THREAD

**Issue by panhezeng** [vuejs/composition-api#464]
TypeError: Cannot read property 'constructor' of undefined
    at getVueInternalClasses (/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:171:50)
    at computed (/node_modules/@vue/composition-api/dist/vue-composition-api.common.js:1034:18)
    at setup (

   // to get Watcher class
        var Watcher = vm._computedWatchers.value.constructor;

ssr renderComponent
go back 1.0.0-beta.6 no error

**Comment by pikax** [comment]
Most likely caused by https://github.com/vuejs/composition-api/pull/452

Can you provide a reproducible repo? 

Is this only when SSR?

**Comment by danielroe** [comment]
It definitely occurs in SSR.

https://codesandbox.io/s/exciting-bhabha-d7i1h?file=/pages/index.vue
